import type { Metadata } from "next";
import { Domine } from "next/font/google";
import "./globals.css";


const domine = Domine({
  subsets: ["latin"],
  variable: "--font-domine",
  weight: ["400", "500", "600", "700"], // optional, pick what you need
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${domine.variable} antialiased bg-black`}
      >
        <div className="max-w-[1400px] mx-auto my-16 w-full bg-background min-h-screen">
          {children}
        </div>
      </body>
    </html>
  );
}
